### ISSUE TITLE
번역 시 고려할 사항

### ISSUE THREAD

**Issue by swb8812** [18-2-SKKU-OSS/2018-2-OSS-L7#11]
번역 작업의 통일성을 위해 토의가 필요함

전문적인 단어나 pull request나 commit같은 통상적인 단어를 번역할지 아니면 그대로 둘지?

**Comment by hancheng1995** [comment]
의미를 훼손하지 않는다면 그냥 번역해도 상관없을것 같아요

**Comment by hancheng1995** [comment]
완전히 이프로젝트에서 만들어진 고유명사면 그대로 냅둬야 할 것 같네요

**Comment by swb8812** [comment]
고유명사를 제외하고는 번역을 하도록 해야겠네요
